version: '3'

services:
    db:
        container_name: db
        image: postgres
    web:
        container_name: web
        build: .
        volumes: 
            - .:/code
        env_file: .env
        entrypoint: ./start.sh
        command: gunicorn config.wsgi --bind 0.0.0.0:80
        ports:
            - "80:80"
        depends_on:
            - db